#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\SRLayer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\RLLayer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\RLayer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\LLayer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\SLayer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\X1Layer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\X2Layer.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\layer\Basic.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\Space.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\RButton.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\LButton.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\RControl.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\RShift.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\XButton1.ahk
#Include, %A_ScriptDir%\src\MouseTyping\hotkey\XButton2.ahk